### การ import pandas

In [1]:
import numpy as np
import pandas as pd

### การกำหนดข้อมูลให้แก่ Series
คำสั่ง **pd.Series(data,index,name,dtype)** โดยส่วนที่จำเป็นต้องกำหนดมีแค่ data ส่วนอื่นไม่ต้องกำหนดก็ได้ใช้ค่า default  
**dtpye** = int64 float64 object bool datetime64 timedelta

#### การกำหนดข้อมูลแบบ sequence ของ python
- ควรกำหนดเป็นข้อมูลแบบ 1 มิติ ไม่เช่นนั้นจะทำให้ถูกซ้อนอยู่ชั้นในและถูกมองเป็นรายการเดียวกัน
- สามารถใช้ฟังชันก์ range ก็ได้ถ้าข้อมูลต่อเนื่องกัน
- ถ้าเป็น dictionary จะนำค่าคีย์มาเป็น index

In [2]:
a1 = pd.Series([1,2,3]) # list
a2 = pd.Series((10,20,30)) # tuple
a3 = pd.Series(range(1,5)) # range

tmp1 = ["100","200","300"] 
a4 = pd.Series(tmp1)
a5 = pd.Series({"a":100,"b":200}) # dictionary
a6 = pd.Series(data=[9,99,999],index=[1,2,3],name="panda",dtype="int64") # กำหนดแบบเต็ม
a7 = pd.Series([[1,2,3],[4,5,6],[7,8,9]])

display(a1,a2,a3,a4,a5,a6,a7)

0    1
1    2
2    3
dtype: int64

0    10
1    20
2    30
dtype: int64

0    1
1    2
2    3
3    4
dtype: int64

0    100
1    200
2    300
dtype: object

a    100
b    200
dtype: int64

1      9
2     99
3    999
Name: panda, dtype: int64

0    [1, 2, 3]
1    [4, 5, 6]
2    [7, 8, 9]
dtype: object

#### การกำหนดข้อมูลด้วย numpy

In [3]:
n1 = np.array([1,2,3])
n2 = np.random.randint(1,20,3)
n3 = np.linspace(1,10,4,dtype="int")

a8 = pd.Series(n1)
a9 = pd.Series(n2)
a10 = pd.Series(n3)

display(a8,a9,a10)

0    1
1    2
2    3
dtype: int32

0    18
1    19
2    18
dtype: int32

0     1
1     4
2     7
3    10
dtype: int32

### การกำหนด index
- หากไม่กำหนด defalut จะเป็น 0,1,2,3,....
- สามารถกำหนด index ได้จะเป็นสตริงหรือตัวเลขก็ได้ แต่ต้องมีค่า**เท่ากับรายการข้อมูล**

In [4]:
a11 = pd.Series([1,2,3],[10,20,30])
a12 = pd.Series([100,150,200],["a","b","c"])
a13 = pd.Series([95,96,97],index=list("xyz"))
display(a11,a12,a13)

10    1
20    2
30    3
dtype: int64

a    100
b    150
c    200
dtype: int64

x    95
y    96
z    97
dtype: int64

### การเข้าถึงและอ้างอิงลำดับข้อมูล แบบปกติ
#### แอตทริบิวต์ values และ index

In [5]:
a14 = pd.Series([300,600,900])
print(a14.index , a14.values , sep="\n")
display()
print("--------------------------------------")
a15 = pd.Series({"x":200,"y":400,"z":600})
print(a15.index , a15.values , sep="\n")
print("--------------------------------------")

RangeIndex(start=0, stop=3, step=1)
[300 600 900]
--------------------------------------
Index(['x', 'y', 'z'], dtype='object')
[200 400 600]
--------------------------------------


#### หากต้องการอ้างถึงค่ารายการในลำดับ มีทางเลือกดังนี้
- ระบุ index แบบลิสหรืออาร์เรย์
- ระบุด้วยชื่อ index
- ถ้าหากว่ากำหนด index ด้วย ค่าตัวเลขจำนวนเต็ม ตอนอ้างถึงก็ต้องใช้ลำดับที่สร้างขึ้น ห้ามใช้ค่า defalut 0,1,2,3.....

In [6]:
print(a14[0],a14[1],a14[2]) # กณีใน bullet point ที่ 3
print(a14.values[0],a14.values[1],a14.values[2])
print("------------------------------")
print(a15[0],a15[1],a15[2])
print(a15.values[0],a15.values[1],a15.values[2])
print(a15["x"],a15["y"],a15["z"])

300 600 900
300 600 900
------------------------------
200 400 600
200 400 600
200 400 600


#### หากต้องการอ่านค่า index

In [7]:
print(a14.index)
print(a14.index[0],a14.index[1],a14.index[2])
print("------------------------------")
print(a15.index)
print(a15.index[0],a15.index[1],a15.index[2])

RangeIndex(start=0, stop=3, step=1)
0 1 2
------------------------------
Index(['x', 'y', 'z'], dtype='object')
x y z


### การอ้างสมาชิกแบบ Fancy Index
- คล้ายกับที่กำหนดใน numpy

In [8]:
n4 = np.random.randint(1,20,5)
a16 = pd.Series(n4)
print(a16,a16[[1,2,3]],sep="\n\n")
print("------------------------------")
n5 = np.random.choice([11,22,33,44,55],5)
a17 = pd.Series(n5,list("abcde"))
print(a17,a17[["d","e"]],sep="\n\n")

0    18
1    18
2    12
3    10
4     1
dtype: int32

1    18
2    12
3    10
dtype: int32
------------------------------
a    22
b    33
c    55
d    44
e    44
dtype: int32

d    44
e    44
dtype: int32


### การอ้างถึงสมาชิกแบบ Index Slicing
- อ้างอิงลำดับแบบไม่มีการกำหนด index **start:stop:step โดยตัวสุดท้ายจะไม่ถึงตัว stop**
- อ้างอิงลำดับแบบมีการกำหนด index **start:stop:step โดยตัวสุดท้ายจะถึงตัว stop**

In [9]:
a18 = pd.Series(np.random.randint(1,100,10))
display(a18 , a18[0:5] , a18[1:10:3] , a18[-1:-5:-1])

0    39
1    68
2    40
3    48
4    11
5    64
6    75
7    94
8    89
9     2
dtype: int32

0    39
1    68
2    40
3    48
4    11
dtype: int32

1    68
4    11
7    94
dtype: int32

9     2
8    89
7    94
6    75
dtype: int32

In [10]:
a18 = pd.Series(np.random.randint(1,100,5),list("abcde"))
display(a18 , a18["a":"b"] , a18["a"::2] , a18["b":"d"] , a18["e":"b":-1])

a    73
b    34
c    82
d    97
e    65
dtype: int32

a    73
b    34
dtype: int32

a    73
c    82
e    65
dtype: int32

b    34
c    82
d    97
dtype: int32

e    65
d    97
c    82
b    34
dtype: int32

### การกำหนดช่วงลำดับแบบ loc
- **Position Index** คือลำดับแบบ 0,1,2,3... เมื่อเราสร้างออบเจ็กต์ Series ก็จะมี Index ประเภทนี้อัตโนมัต ถึงแม้จะกำหนด index ใหม่ ก็ยังสามารถอ้างอิงด้วย ลำดับแบบ 0,1,2,3... ได้
- **Label Index** คือที่เรากำหนดลำดับอ้างอิงใหม่

**สังเกตุว่า** เมื่อเราสร้าง Series พร้อมกำหนดตัวเลขแบบ label index จากนั้นอ้างสมาชิกแบบ index slicing มันจะพิจารณาตามเลข position index

In [11]:
a19 = pd.Series(np.array([22,44,66,88,99]),[1,3,5,7,9])
display(a19,a19[3:10])

1    22
3    44
5    66
7    88
9    99
dtype: int32

7    88
9    99
dtype: int32

โอเปอเรเตอร์ **loc** ใช้ในการระบุช่วงแบบ label index
- อ้างอิงลำดับแบบมีการกำหนด index **start:stop:step โดยตัวสุดท้ายจะถึงตัว stop**
- กรณี index เป็นอักขระไม่จำเป็นต้องใช้ loc ก็ได้ ดังหัวข้อที่แล้ว

In [12]:
display(a19.loc[1],a19.loc[3],a19.loc[3:9],a19.loc[[1,7,9]])

22

44

3    44
5    66
7    88
9    99
dtype: int32

1    22
7    88
9    99
dtype: int32

### การจัดการข้อมูลด้วยโอเปอเรเตอร์
- (+ - * ** / // %) ดำเนินเกี่ยวกับค่าคงที่ หรือ series ด้วยกันเองก็ได้
- การดำเนินการระหว่าง series จะเกิดขึ้นเฉพาะรายการที่มี index ตรงกันเท่านั้น (หากเป็นอักขระต้องเขียนในรูปแบบพิมพ์เดียวกัน)
- การเรียงลำดับ index ไม่จำเป็นต้องตรงกัน
- รายการที่กำหนด index ไม่ตรงกันรายการนั้นจะได้ค่า NaN

In [13]:
a20 = pd.Series(np.random.randint(10,100,3),list("abc"))
a21 = pd.Series(np.random.randint(10,100,3),list("abc"))
a22 = pd.Series(np.random.randint(10,100,3),list("cba"))
a23 = pd.Series(np.random.randint(10,100,3),list("zba"))

display(a20 , a20+10 , a20//2)
print("------------------------------")
display(a21 , a22 , a21+a22)
print("------------------------------")
display(a22 , a23 , a22+a23)

a    75
b    45
c    56
dtype: int32

a    85
b    55
c    66
dtype: int32

a    37
b    22
c    28
dtype: int32

------------------------------


a    94
b    53
c    26
dtype: int32

c    44
b    29
a    57
dtype: int32

a    151
b     82
c     70
dtype: int32

------------------------------


c    44
b    29
a    57
dtype: int32

z    98
b    59
a    93
dtype: int32

a    150.0
b     88.0
c      NaN
z      NaN
dtype: float64

In [14]:
a24 = pd.Series(np.random.randint(10,100,3))
a25 = pd.Series(np.random.randint(10,100,3))
a26 = pd.Series(np.random.randint(10,100,3))

display(a24 , a24+10 , a24//2)
print("------------------------------")
display(a25 , a26 , a25+a26)

0    88
1    68
2    60
dtype: int32

0    98
1    78
2    70
dtype: int32

0    44
1    34
2    30
dtype: int32

------------------------------


0    10
1    98
2    73
dtype: int32

0    24
1    98
2    84
dtype: int32

0     34
1    196
2    157
dtype: int32

In [15]:
a27 = pd.Series(np.random.randint(1,100,10))
a28 = a27[a27 > 50]
a29 = a27[(a27 > 50) & (a27 % 5 == 0)]
a30 = a27[(a27 < 20) | (a27 > 80)]
display(a27,a28,a29,a30)

0    88
1    51
2    36
3    18
4    93
5    79
6    64
7    31
8    95
9    20
dtype: int32

0    88
1    51
4    93
5    79
6    64
8    95
dtype: int32

8    95
dtype: int32

0    88
3    18
4    93
8    95
dtype: int32

### ฟังชันก์ที่น่าสนใจขอบอ็อบเจ็ค Series
- **sum** หาผลรวมของสมาชิกทั้งหมด

In [16]:
a31 = pd.Series(np.array((1,2,3,4,5)))
display(a31)
print("sum =",a31.sum())

0    1
1    2
2    3
3    4
4    5
dtype: int32

sum = 15


- **count**   นับจำนวนรายการข้อมูลทั้งหมด (ไม่นับ NaN)
- **size**    นับจำนวนรายการข้อมูลทั้งหมด (นับ NaN)
- **std**     หาส่วนเบี่ยงเบนมาตราฐาน
- **mean**    หาค่าเฉลี่ยของข้อมูล
- **min**     หาค่าน้อยสุด
- **max**     หาค่ามากสุด
- **describe**ใช้แสดงค่าพื้นฐานทางสถิติ หรือเทียบเท่าการใช้งานคำสั่งด้านบน

In [17]:
a31 = pd.Series(np.array([2,4,6,8,10]))
print(a31,end="\n\n")
print("count =" , a31.count())
print("mean =" , a31.mean())
print("std =" , a31.std())
print("min =" , a31.min())
print("max =" , a31.max())
print()
print(a31.describe())

0     2
1     4
2     6
3     8
4    10
dtype: int32

count = 5
mean = 6.0
std = 3.1622776601683795
min = 2
max = 10

count     5.000000
mean      6.000000
std       3.162278
min       2.000000
25%       4.000000
50%       6.000000
75%       8.000000
max      10.000000
dtype: float64


- **idxmin**   แสดง index ของข้อมูลน้อยสุด
- **idxmax**   แสดง index ของข้อมูลมากสุด

In [18]:
a32 = pd.Series(np.array([9,65,32,3,4]))
print("index min = ",a32.idxmin())
print("index max = ",a32.idxmax())

index min =  3
index max =  1


- **any**   ใช้ตรวจสอบข้อมูลทั้งหมด ที่ตรงเงื่อนไข  คืนค่าเป็น true/false
- **all**   ใช้ตรวจสอบข้อมูลบางส่วน ที่ตรงเงื่อนไข คืนค่าเป็น true/false

In [19]:
a33 = pd.Series(np.random.randint(1,101,5))
display(a33 , (a33 > 20).all() , (a33 > 20).any())

0    14
1    16
2    35
3     9
4    63
dtype: int32

False

True

- **concat** ใช้ผนวกข้อมูลระหว่าง 2 Series มาเชื่อมด้วยกัน
- **หมายเหตุ** append จะถูกนำออกใน pandas เวอชันต่อไป

In [20]:
a34 = pd.Series(np.array([1,2,3]),list("abc"))
a35 = pd.Series(np.array([4,5,6]),list("def"))
a36 = pd.concat([a34,a35])
print(a36)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int32


- **apply** สร้างฟังชันก์แล้วเรียกขึ้นมาทำงาน เพื่อจัดการข้อมูลทีละรายการ


In [21]:
def func(x):
    return x*(-1) if x < 0 else x

a37 = pd.Series(np.random.randint(-101,101,5))
a38 = a37.apply(func)
display(a37,a38)

0   -18
1   -21
2   -82
3   -27
4   -99
dtype: int32

0    18
1    21
2    82
3    27
4    99
dtype: int64

- **unique**   เลือกรายการข้อมูลไม่ซ้ำกัน ได้ผลลัพธ์แบบลิส
- **nunique**    นับจำนวนรายการข้อมูลแบบไม่ซ้ำกัน (ถ้าซ้ำกันนับแค่ครั้งเดียว)
- **is_unique**  ตรวจสอบว่าข้อมูลที่ไม่ซ้ำกันหรือไม่ ถ้าไม่มีจะคืนค่า True
- **value_counts**  นับจำนวนรายการที่ซ้ำกันว่ามีอย่างละกี่รายการ เสมือนการจัดกลุ่มข้อมูลที่ซ้ำกัน

In [22]:
a39 = pd.Series(np.array([1,1,1,2,2,3,4,5,5,6,7]))
display(a39.unique() , a39.nunique() , a39.is_unique , a39.value_counts())

array([1, 2, 3, 4, 5, 6, 7])

7

False

1    3
2    2
5    2
3    1
4    1
6    1
7    1
dtype: int64

- **head**  แสดงรายการแรก ตามจำนวนที่ระบุ
- **tail**  แสดงรายการสุดท้าย ตามจำนวนที่ระบุ  

In [23]:
a40 = pd.Series(np.random.randint(1,10,20))
display(a40 , a40.head(5) , a40.tail(5))

0     9
1     9
2     1
3     8
4     3
5     3
6     1
7     3
8     2
9     5
10    2
11    9
12    7
13    8
14    3
15    6
16    5
17    8
18    6
19    2
dtype: int32

0    9
1    9
2    1
3    8
4    3
dtype: int32

15    6
16    5
17    8
18    6
19    2
dtype: int32

- **drop**  ลบข้อมูลออกจาก Series ผลลัพธ์ที่ได้คือ ออบเจ็กต์ Series ของรายการที่ยังเหลืออยู่

In [24]:
a41 = pd.Series(np.random.randint(1,10,5))
a42 = a41.drop(4)
display(a41,a42)

0    8
1    6
2    3
3    9
4    1
dtype: int32

0    8
1    6
2    3
3    9
dtype: int32

- **map** แก้ไขรายการของข้อมูลของ series หลายๆอันพร้อมกัน โดย map ค่าที่ตรงกันในแบบดิกชันนารี คือ {ค่าเดิม:ค่าใหม่} ส่วนค่าไม่ตรงกันจะกลายเป็น NaN

In [25]:
a43 = pd.Series([10,20,30,40])
a44 = a43.map({10:100 , 20:200})

display(a43,a44)

0    10
1    20
2    30
3    40
dtype: int64

0    100.0
1    200.0
2      NaN
3      NaN
dtype: float64

- **rename** แก้ไขชื่อ index โดยจับคู่ index ที่ตรงกันในแบบดิกชันนารี

In [26]:
a45 = pd.Series(np.array([10,20,30,40]))
a46 = a45.rename({0:10 , 1:100 , 2:1000 , 3:10000})

# หากต้องการเปลี่ยนชื่อทั้งหมด อาจจะกำหนดผ่านแอตทริบิวต์
# a46.index = ["one","two","three","four"]

display(a45,a46)

0    10
1    20
2    30
3    40
dtype: int32

10       10
100      20
1000     30
10000    40
dtype: int32

- **sort_values** เรียงลำดับข้อมูลปกติ ปกติจะเรียงจากน้อยไปหามาก แต่ถ้าต้องการเรียงจากมากไปหาน้อย ให้ระบุ **ascending=False** (ถ้าเป็น True จะเรียงจากน้อยไปมาก)
- **iteritems** สำหรับเข้าถึงรายการข้อมูลทั้งหมดด้วยลูป เช่นเดียวกับฟังชันก์ enumerate ของ python 

In [27]:
a47 = pd.Series(np.random.randint(1,100,5))
display(a47 , a47.sort_values() , a47.sort_values(ascending=False))

for (i,e) in a47.iteritems():
    print(f"{i}:{e}")

0    42
1    94
2    88
3    86
4    41
dtype: int32

4    41
0    42
3    86
2    88
1    94
dtype: int32

1    94
2    88
3    86
0    42
4    41
dtype: int32

0:42
1:94
2:88
3:86
4:41


### ข้อมูลที่มีค่า NaN
- ใน numpy มีการกำหนดค่า NaN ด้วย np.nan
- หากเราคำนวนค่า NaN ก็จะได้ผลลัพธ์ NaN ตามเดิม

In [28]:
a48 = pd.Series([1,2,np.nan,3,np.nan])
display(a48 , a48 + 1 , a48 - 3)

0    1.0
1    2.0
2    NaN
3    3.0
4    NaN
dtype: float64

0    2.0
1    3.0
2    NaN
3    4.0
4    NaN
dtype: float64

0   -2.0
1   -1.0
2    NaN
3    0.0
4    NaN
dtype: float64

- สามารถกำหนด อาร์กิวเมนต์ **skipna=False** เมื่อต้องการให้พิจารณา NaN
- เมื่อกำหนดแล้วหากใน Series มีหลายรายการอย่างน้อยที่เป็น NaN ผลลัพธ์จะเป็น NaN โดยปริยาย

In [29]:
a49 = pd.Series(np.array([2,4,6,8,10,np.nan,np.nan]))
print(a31,end="\n\n")
print("sum =" , a49.sum())
print("count =" , a49.count())
print("size =" , a49.size)
print("mean =" , a49.mean())
print("std =" , a49.std())
print("min =" , a49.min())
print("max =" , a49.max())
print()
print("sum =" , a49.sum(skipna=False))
print("count =" , a49.count())
print("mean =" , a49.mean(skipna=False))
print("std =" , a49.std(skipna=False))
print("min =" , a49.min(skipna=False))
print("max =" , a49.max(skipna=False))

0     2
1     4
2     6
3     8
4    10
dtype: int32

sum = 30.0
count = 5
size = 7
mean = 6.0
std = 3.1622776601683795
min = 2.0
max = 10.0

sum = nan
count = 5
mean = nan
std = nan
min = nan
max = nan


- **dropna** ลบรายการข้อมูลที่มีค่า NaN ทิ้งไป
- **fillna** เปลี่ยนรายการข้อมูลที่มีค่า NaN ให้เป็นค่าใหม่ โดยกำหนดค่าเป็นอาร์กิวเมนต์
- **hasnans** มีรายการที่เป็น NaN อยู่หรือไม่ ถ้ามีอย่างน้อย 1 รายการจะได้เป็นค่าเป็น True

In [30]:
a50 = pd.Series(np.array([2,4,6,8,10,np.nan,np.nan]))
a51 = pd.Series(np.array([2,4,6,8,10]))

display(a50 , a50.dropna() , a50.fillna(30) , a50.hasnans , a51.hasnans)

0     2.0
1     4.0
2     6.0
3     8.0
4    10.0
5     NaN
6     NaN
dtype: float64

0     2.0
1     4.0
2     6.0
3     8.0
4    10.0
dtype: float64

0     2.0
1     4.0
2     6.0
3     8.0
4    10.0
5    30.0
6    30.0
dtype: float64

True

False