### การ import numpy

In [1]:
import numpy as np

### การสร้างอาร์เรย์ และการระบุชนิดข้อมูล
- type int , uint , float

In [242]:
a1 = np.array([1,2,3,4,5] , dtype="float32")
a2 = np.array([1.1,2.2,3.3] , dtype="uint32")
a3 = np.array([-1,-2,-3] , dtype="int32")
a4 = np.array(range(1,10) , dtype="int32")
a5 = np.array([x*3 for x in range(1,5)] , dtype="int32")

print(a1 , a2 , a3 , a4, a5 ,sep="\n")

[1. 2. 3. 4. 5.]
[1 2 3]
[-1 -2 -3]
[1 2 3 4 5 6 7 8 9]
[ 3  6  9 12]


- type boolean , string

In [243]:
a6 = np.array([True,False,True] , dtype="bool")
a7 = np.array(['a','b','c'])

print(a6 , a7 , sep="\n")    

[ True False  True]
['a' 'b' 'c']


- แปลงชนิดข้อมูลด้วยฟังชันก์ **astype()** 

In [245]:
a8 = np.array([10,20,30,40,50] , dtype="int32")
a9 = a8.astype("float32")

a10 = np.array([True , True , False] , dtype="bool")
a11 = a10.astype("uint32")

print(a9 , a11 , sep="\n")

[10. 20. 30. 40. 50.]
[1 1 0]


### การสร้างอาร์เรย์แบบใช้ข้อมูลเดียวกัน
- **zeros(size,dtype)** 0 หมด
- **ones(size,dtype)**  1 หมด
- **full(size,value)**  กำหนดค่าที่ต้องการ

In [5]:
a12 = np.zeros(5)
a13 = np.ones(5)
a14 = np.full(5,20)
a15 = np.ones(3,dtype="int32")

print(a12 , a13 , a14 , a15 , sep="\n")

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[20 20 20 20 20]
[1 1 1]


### การสร้างอาร์เรย์แบบกำหนดช่วงข้อมูล
- **arange(start,stop,step)** เหมือนฟังชันก์ range ของ python
- **linspace(begin,end,size)** จะได้ผลลัพธ์เป็น float ต้องกำหนด dtype เพื่อให้ได้ชนิดข้อมูลที่ต้องการ

In [6]:
a16 = np.arange(1,10,2)
a17 = np.arange(10,0,-3)
a18 = np.arange(1,5,0.5)
a19 = np.linspace(1,10,5 ,dtype="int32")
a20 = np.linspace(15,5,3 ,dtype="int32")

print(a16 , a17 , a18 , a19 , a20 , sep="\n")

[1 3 5 7 9]
[10  7  4  1]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 1  3  5  7 10]
[15 10  5]


### การสร้างอาร์เรย์จากเลขสุ่ม
- **randint(low,high,size)** สุ่มช่วงจำนวนเต็ม
- **uniform(low,high,size)** สุ่มช่วงจำนวนทศนิยม
- **rand(size)** สุ่มช่วง 0-1
- **choice(sequence,size)** สุ่มจากตัวเลือกที่กำหนด

In [7]:
a21 = np.random.randint(1,10,3)
a22 = np.random.uniform(1,10,3)
a23 = np.random.rand(3)
a24 = np.random.choice(["john","sura","sarun","jack","bell"],3)
a25 = np.random.randint(-10,11,5)

print(a21 , a22 , a23 , a24 , a25 , sep="\n")

[8 5 9]
[1.31350749 5.38145734 2.87333101]
[0.31745543 0.6439759  0.08285503]
['jack' 'sarun' 'bell']
[ 9 -9 -2 -9  8]


### การเข้าถึงสมาชิกของอาร์เรย์

In [246]:
b = np.array([2,13,7] , dtype="int")
print(b[0],b[1],b[2])
print(b[-1],b[-2],b[-3])

2 13 7
7 13 2


### Index Slicing

In [252]:
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[0:])
print(c[:9])
print(c[2:5])
print(c[1:10:2])
print(c[-10:-1])
print(c[-3:-9:-1])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7 8 9]
[3 4 5]
[ 2  4  6  8 10]
[1 2 3 4 5 6 7 8 9]
[8 7 6 5 4 3]


### Fancy Indexing

In [10]:
d = np.array([1,2,3,4,5,6,7,8,9,10])
fancy1 = [0,2,4]
fancy2 = [-1,-4,-6]

print(d[fancy1])
print(d[fancy2])

[1 3 5]
[10  7  5]


### จัดการอาร์เรย์ด้วยโอเปอเรเตอร์ทางคณิตศาสตร์
- สามารถดำเนินการระหว่างอาเรย์ได้เลย แต่อาเรย์ทั้งสองอันต้องมีสมาชิกเท่ากัน
- ดำเนินการสมาชิกบางส่วน
- ทำการกรองข้อมูลตามเงื่อนไข

In [253]:
e = np.random.randint(1,50,5)
f = np.random.randint(1,50,5)

print(e)
print(f)
print("----------------------")

g1 = e + 10
print(g1)
print("----------------------")

g2 = e - f
print(g2)
print("----------------------")

g3 = e[:3] * 2
g4 = e[1:5:2] + 2
g5 = e[[2,4]] + 5
print(g3,g4,g5,sep="\n")
print("----------------------")

g6 = e[(e > 20) | (e % 5 == 0)]
g7 = e[(e >= 5) & (e <= 15 )]

print(g6,g7,sep="\n")


[16 35 19  8 31]
[40 43 37 20 17]
----------------------
[26 45 29 18 41]
----------------------
[-24  -8 -18 -12  14]
----------------------
[32 70 38]
[37 10]
[24 36]
----------------------
[35 31]
[8]


### การร้างอาร์เรย์แบบ 2 มิติ
- กำหนดแบบ **แถว** และ **คอลัมน์** เหมือน matrix

In [256]:
h1 = np.array([[10,20,30],
              [40,50,60],
              [10,20,30]])

list1 = [[1,2,3],[4,5,6],[7,8,9]]
h2 = np.array(list1)

h3 = np.ones([3,3],dtype="int")
h4 = np.zeros([3,3],dtype="int")
h5 = np.full([3,3],10)
h6 = np.random.randint(1,21,[3,3])
h7 = np.random.uniform(1,21,[3,3])
h8 = np.random.rand(3,3)
h9 = np.random.choice([1,2,3,4,5],[3,3])

print(h1,h2,h3,h4,h5,h6,h7,h8,h9,sep="\n\n")

[[10 20 30]
 [40 50 60]
 [10 20 30]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[10 10 10]
 [10 10 10]
 [10 10 10]]

[[13  1 17]
 [10  3 19]
 [ 7  7 20]]

[[ 2.62496745  9.08548677  2.59158089]
 [20.04045556  1.48601764 17.70663195]
 [17.05718966  7.32724345 13.57555595]]

[[0.44177889 0.23216739 0.13130969]
 [0.16311201 0.78798793 0.88716969]
 [0.75346982 0.84006423 0.00306145]]

[[3 2 5]
 [5 5 5]
 [4 1 5]]


### การเข้าถึงอาร์เรย์แบบ 2 มิติ

In [262]:
j = np.random.randint(20,51,[5,5])
print(j,end="\n\n")
print(j[0])
print(j[1])
print(j[0,0])
print(j[4,4])
print(j[3,2])


print(j[1:3,1:5] , j[:,::2] , sep="\n\n")

[[33 35 25 27 21]
 [24 22 30 43 48]
 [46 41 23 22 38]
 [30 31 26 49 34]
 [44 30 35 45 28]]

[33 35 25 27 21]
[24 22 30 43 48]
33
28
26
[[22 30 43 48]
 [41 23 22 38]]

[[33 25 21]
 [24 30 48]
 [46 23 38]
 [30 26 34]
 [44 35 28]]


### การจัดการอาร์เรย์ 2 มิติด้วยโอเปอเรเตอร์
- สามารถดำเนินการระหว่างอาเรย์ได้เลย แต่อาเรย์ทั้งสองต้องมีแถวและคอลัมน์เท่ากัน
- ทำการกรองข้อมูลตามเงื่อนไข แต่จะได้เป็นอาเรย์มิติเดียว

In [14]:
k = np.random.randint(10,21,[3,3])
l = np.random.randint(10,21,[3,3])

print(k,l,k+10,k-5,k+l,sep="\n\n")
print("--------------------")

m1 = k[k > 15]
m2 = k[(k > 10) & (k < 15)]

print(m1,m2,sep="\n\n")

[[11 14 14]
 [18 13 17]
 [17 13 11]]

[[19 10 17]
 [20 16 18]
 [15 18 16]]

[[21 24 24]
 [28 23 27]
 [27 23 21]]

[[ 6  9  9]
 [13  8 12]
 [12  8  6]]

[[30 24 31]
 [38 29 35]
 [32 31 27]]
--------------------
[18 17 17]

[11 14 14 13 13 11]


### Universal Function ของ Numpy
axis = 0 แถวตั้ง
axis = 1 แถวนอน

- **sum**
    - หาผลรวมของสมาชิก

In [263]:
n1 = np.array([1,3,5,7,9])
n2 = np.sum(n1)
print(n2)

25


In [265]:
n3 = np.random.randint(1,20,[3,3])
n4 = np.sum(n3,axis=0)
n5 = np.sum(n3,axis=1)
n6 = np.sum(n3)
print(n3,end="\n\n")
print(n4,n5,n6,sep="\n\n")

[[11 14  5]
 [12  7 19]
 [18  6  3]]

[41 27 27]

[30 38 27]

95


- **cumsum**
    - หาผลบวกสะสมของสมาชิก

In [266]:
n7 = np.array([10,15,20,25])
n8 = np.cumsum(n7)
print(n7)
print(n8)

[10 15 20 25]
[10 25 45 70]


In [18]:
n9 = np.random.randint(1,20,[3,3])
n10 = np.cumsum(n9,axis=0)
n11 = np.cumsum(n9,axis=1)
n12 = np.cumsum(n9)
print(n9,end="\n\n")
print(n10,n11,n12,sep="\n\n")

[[ 4 14 10]
 [ 2  7  9]
 [ 4  2  7]]

[[ 4 14 10]
 [ 6 21 19]
 [10 23 26]]

[[ 4 18 28]
 [ 2  9 18]
 [ 4  6 13]]

[ 4 18 28 30 37 46 50 52 59]


- **mean**
    - หาค่าเฉลี่ยของสมาชิก

In [267]:
n13 = np.array([5,10,15,30])
n14 = np.mean(n13)
print(n13)
print(n14)

[ 5 10 15 30]
15.0


In [23]:
n15 = np.random.randint(1,20,[3,3])
n16 = np.mean(n15,axis=0)
n17 = np.mean(n15,axis=1)
n18 = np.mean(n15)
print(n15,end="\n\n")
print(n16,n17,n18,sep="\n\n")

[[ 5  5 13]
 [12 11 10]
 [13  3 16]]

[10.          6.33333333 13.        ]

[ 7.66666667 11.         10.66666667]

9.777777777777779


- **min**
    - หาค่าต่ำสุดของสมาชิก
- **max**
    - หาค่าสูงสุดของสมาชิก

In [270]:
n19 = np.random.randint(1,10,5)
n20 = np.min(n19)
n21 = np.max(n19)
print(n19,n20,n21,sep="\n")

[7 6 4 9 2]
2
9


In [271]:
n22 = np.random.randint(1,20,[3,3])
n23 = np.min(n22,axis=0)
n24 = np.min(n22,axis=1)
n25 = np.max(n22,axis=0)
n26 = np.max(n22,axis=1)
n27 = np.min(n22)
n28 = np.max(n22)
print(n22,n23,n24,n25,n26,n27,n28,sep="\n\n")

[[15 13 15]
 [19  8  4]
 [ 5 11 17]]

[5 8 4]

[13  4  5]

[19 13 17]

[15 19 17]

4

19


- **sort**
    - เรียงลำดับจากน้อยไปมาก ควรระบุแนวแกน(axis)ทุกครั้ง

In [272]:
n29 = np.arange(20,1,-2)
n30 = np.sort(n29)
print(n29,n30,sep="\n")

[20 18 16 14 12 10  8  6  4  2]
[ 2  4  6  8 10 12 14 16 18 20]


In [89]:
n31 = np.random.randint(1,20,[3,3])
n32 = np.sort(n31,axis=0)
n33 = np.sort(n31,axis=1)

print(n31,n32,n33,sep="\n\n")

[[ 4 13 10]
 [ 3  1 11]
 [18  6 17]]

[[ 3  1 10]
 [ 4  6 11]
 [18 13 17]]

[[ 4 10 13]
 [ 1  3 11]
 [ 6 17 18]]


- **unique**
    - ไม่ต้องกำหนด axis

In [94]:
n34 = np.random.choice([1,2,3,4,5],10)
n35 = np.unique(n34)

n36 = np.random.randint(1,21,[4,4])
n37 = np.unique(n36)

print(n34,n35,n36,n37,sep="\n\n")


[2 5 1 4 4 3 5 1 1 3]

[1 2 3 4 5]

[[ 2 20  5 10]
 [20 13  1 14]
 [ 8 20  4 14]
 [ 2 16 13 18]]

[ 1  2  4  5  8 10 13 14 16 18 20]


- **concatenate** (นำสมาชิกของอาเรย์สองอาเรย์มาผนวกเป็นสมาชิกเดียวกัน)
    - ถ้าอาเรย์เป็นคนละชนิด เช่น int กับ float อาเรย์จะถูกแปลงเป็นชนิด float

In [109]:
n38 = np.array([1,2,3,4,5])
n39 = np.array([6,7,8,9,10])
n40 = np.concatenate([n38,n39])

n41 = np.random.randint(1,10,[2,2])
n42 = np.random.uniform(11,20,[2,2])
n43 = np.concatenate([n41,n42])

print(n40,n41,n42,n43,sep="\n\n")

[ 1  2  3  4  5  6  7  8  9 10]

[[4 1]
 [9 5]]

[[11.54200713 16.53187132]
 [14.99562159 17.92414994]]

[[ 4.          1.        ]
 [ 9.          5.        ]
 [11.54200713 16.53187132]
 [14.99562159 17.92414994]]


- **vstack**
    - ผนวกอาเรย์ซ้อนกันในแนวตั้ง
    - ใช้ได้กับอาเรย์ที่มีขนาดเดียวกันเท่านั้น
- **hstack**
    - ผนวกอาเรย์ซ้อนกันในแนวนอน
    - ใช้ได้กับอาเรย์ที่มีขนาดเดียวกันเท่านั้น
    

In [115]:
n44 = np.array([1,2,3,4])
n45 = np.array([6,7,8,9])
n46 = np.vstack([n44,n45])
n47 = np.hstack([n44,n45])

n48 = np.full([2,2],5)
n49 = np.full([2,2],9)
n50 = np.vstack([n48,n49])
n51 = np.hstack([n48,n49])

print(n46,n47,n48,n49,n50,n51,sep="\n\n")

[[1 2 3 4]
 [6 7 8 9]]

[1 2 3 4 6 7 8 9]

[[5 5]
 [5 5]]

[[9 9]
 [9 9]]

[[5 5]
 [5 5]
 [9 9]
 [9 9]]

[[5 5 9 9]
 [5 5 9 9]]


- **view**
    - เป็นการคัดลอกแบบ shallow copy ถ้าหากเปลี่ยนแปลงสมาชิกอาเรย์หนึ่ง จะส่งผลให้อีกอาเรย์หนึ่งเปลี่ยนแปลงไปด้วย

In [167]:
n51 = np.random.randint(1,10,[3,3])
n52 = n51.view()

n51[0] = 100
n52[1] = 200
print(n51,n52,sep="\n\n")

[[100 100 100]
 [200 200 200]
 [  9   9   3]]

[[100 100 100]
 [200 200 200]
 [  9   9   3]]


- **copy**
    - เป็นการคัดลอกแบบ deep copy ถ้าหากเปลี่ยนแปลงสมาชิกอาเรย์หนึ่ง จะไม่ส่งผลให้อาเรย์ที่คัดลอกเปลี่ยนแปลงตาม

In [168]:
n53 = np.random.randint(1,10,[3,3])
n54 = n53.copy()

n53[0] = 100
n53[1] = 30
print(n53,n54,sep="\n\n")

[[100 100 100]
 [ 30  30  30]
 [  1   2   2]]

[[1 1 5]
 [6 2 3]
 [1 2 2]]


- **reshape**
    - สามารถเปลี่ยนขนาดของอาเรย์ เช่น 6x4 เป็น 3x8
    - สามารถแก้ไขจากอาเรย์มิติเดียว ให้เป็นสองมิติก็ได้
    - อาเรย์ใหม่ต้องมีสมาชิกเท่ากับอาเรย์เดิม และหากมีการเปลี่ยนแปลงค่าสมาชิกของอาเรย์หนึ่ง จะส่งผลต่ออีกอาเรย์หนึ่งด้วย

In [189]:
n55 = np.arange(20,36)
n56 = np.reshape(n55,[4,4]) # n56 = np.arange(20,36).reshape([4,4])

n57 = np.random.randint(1,20,[3,4])
n58 = np.reshape(n57,(4,3))

n57[0,0] = 100
n58[0,1] = 200

print(n55,n56,n57,n58,sep="\n\n")

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]

[[100 200   7   5]
 [ 14   4  19  18]
 [ 18   5  19   5]]

[[100 200   7]
 [  5  14   4]
 [ 19  18  18]
 [  5  19   5]]


**เพิ่มเติม reshape**
 - การระบุจำนวนแถว หรือ คอลัมน์ อย่างใดอย่างหนึ่ง โดยการกำหนดให้เป็น -1 มีความหมายคือถ้ากำหนด -1 ไปคือการให้ numpy ไปคำนวณจำนวนแถวหรือคอลัมน์นั้นเอง
    

In [208]:
n59 = np.arange(1,13)
n60 = np.reshape(n59,[-1,3]) # [3,3]
n61 = np.reshape(n59,[2,-1]) # [2,6]
print(n59,n60,n61,sep="\n\n")

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


- **resize**
    - สามารถเปลี่ยนขนาดของอาเรย์ เช่น 6x4 เป็น 3x8
    - สามารถแก้ไขจากอาเรย์มิติเดียว ให้เป็นสองมิติก็ได้
    - อาเรย์ใหม่ต้องมีสมาชิกเท่ากับอาเรย์เดิม และหากมีการเปลี่ยนแปลงค่าสมาชิกของอาเรย์หนึ่ง จะไม่ส่งผลต่ออีกอาเรย์หนึ่ง

In [240]:
n62 = np.arange(20,26)
n63 = np.resize(n62,[3,2])

n64 = np.random.randint(1,20,[3,4])
n65 = np.resize(n64,[4,3])

n64[0,0] = 100
n65[0,1] = 200

print(n62,n63,n64,n65,sep="\n\n")

[20 21 22 23 24 25]

[[20 21]
 [22 23]
 [24 25]]

[[100  19   8  11]
 [ 12  14   9  11]
 [  3   4   9   7]]

[[  6 200   8]
 [ 11  12  14]
 [  9  11   3]
 [  4   9   7]]
